services:
  auth-service:
    build:
      context: ./apps/auth-service
    ports:
      - "4001:3001"
    volumes:
      - ./apps/auth-service/src:/app/src

  user-service:
    build:
      context: ./apps/user-service
    ports:
      - "4002:3002"
    volumes:
      - ./apps/user-service/src:/app/src

  exam-service:
    build:
      context: ./apps/exam-service
    ports:
      - "4003:3003"
    volumes:
      - ./apps/exam-service/src:/app/src

  submission-service:
    build:
      context: ./apps/submission-service
    ports:
      - "4004:3004"
    volumes:
      - ./apps/submission-service/src:/app/src

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "4000:3000"

  postgres:
    ports:
      - "5432:5432"
