services:
  gotrue:
    ports:
      - "9999:9999"

  user-service:
    build:
      context: ./apps/user-service
    ports:
      - "4002:3002"
    volumes:
      - ./apps/user-service/src:/app/src

  exam-service:
    build:
      context: ./apps/exam-service
    ports:
      - "4003:3003"
    volumes:
      - ./apps/exam-service/src:/app/src

  submission-service:
    build:
      context: ./apps/submission-service
    environment:
      USER_SERVICE_URL: http://user-service:3002
    ports:
      - "4004:3004"
    volumes:
      - ./apps/submission-service/src:/app/src

  interaction-service:
    build:
      context: ./apps/interaction-service
    ports:
      - "4005:3005"
    volumes:
      - ./apps/interaction-service/src:/app/src

  grader-service:
    build:
      context: ./apps/grader-service
    volumes:
      - ./apps/grader-service/src:/app/src

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "4000:3000"

  postgres:
    ports:
      - "5432:5432"
