events {}

http {
  upstream auth         { server auth-service:3001; }
  upstream users        { server user-service:3002; }
  upstream exams        { server exam-service:3003; }
  upstream submissions  { server submission-service:3004; }
  upstream frontend     { server frontend:3000; }

  server {
    listen 80;

    location /api/auth/ {
      proxy_pass http://auth/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/users/ {
      proxy_pass http://users/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/exams/exams/internal/ {
      return 403;
    }

    location /api/exams/ {
      proxy_pass http://exams/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/submissions/ {
      proxy_pass http://submissions/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
      proxy_pass http://frontend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
