<!--
  Generated by scripts/build-landing-i18n.js from landing/partials/{header,footer}.html
  and landing/partials/chrome.css — do not edit. Change the partial and re-run,
  so the landing pages and these pages keep the same nav and footer.
-->
<script>
  // Absolute, language-aware URLs from $lib/seo.js — see the generator for why
  // they are props rather than the %TOKEN%s the static pages use.
  let { homePath, catalogPath, brandPath, contactPath, t, children } = $props()

  const appLogin = 'https://app.novaquiz.net/login'
</script>

<div class="pub">
<nav>
  <a class="nav-brand" href={homePath}>NovaQuiz</a>
  <div class="nav-links">
    <a href={catalogPath} class="nav-hide">{t('nav.exams')}</a>
    <a href="{homePath}#features" class="nav-hide">{t('nav.features')}</a>
    <a href="{homePath}#security" class="nav-hide">{t('nav.security')}</a>
    <a href="{homePath}#how" class="nav-hide">{t('nav.how')}</a>
    <a href="{homePath}#faq" class="nav-hide">{t('nav.faq')}</a>
    <!-- language switcher: see scripts/build-landing-i18n.js -->
    <a href={appLogin} class="btn-nav">{t('nav.cta')}</a>
  </div>
</nav>

<main class="pub-main">
  {@render children()}
</main>

<footer>
  <div class="footer-links">
    <a href={appLogin}>{t('nav.cta')}</a>
    <span class="footer-divider">·</span>
    <a href={catalogPath}>{t('nav.exams')}</a>
    <span class="footer-divider">·</span>
    <a href="{homePath}#features">{t('nav.features')}</a>
    <span class="footer-divider">·</span>
    <a href="{homePath}#faq">{t('nav.faq')}</a>
    <span class="footer-divider">·</span>
    <a href={brandPath}>{t('nav.brand')}</a>
    <span class="footer-divider">·</span>
    <a href={contactPath}>{t('nav.contact')}</a>
  </div>
  <p style="margin-bottom:.75rem">© 2026 <strong>NovaQuiz</strong> · <span>{t('footer.tagline')}</span></p>
  <p style="font-size:.8rem;opacity:.6">
    <span>{t('footer.builtBy')}</span> <strong style="color:#94a3b8">Trần Phú</strong>
    &nbsp;·&nbsp; <a href="mailto:tranphu.dev@gmail.com" style="color:#94a3b8;text-decoration:none">tranphu.dev@gmail.com</a>
    &nbsp;·&nbsp; <a href="https://novaquiz.net" style="color:#94a3b8;text-decoration:none">novaquiz.net</a>
  </p>
</footer>
</div>

<style>
  /* Tokens come from the :global(:root) block in src/routes/+layout.svelte,
     which is emitted whichever branch that layout renders. */
  .pub { min-height: 100vh; display: flex; flex-direction: column; background: var(--bg); color: var(--text); }
  .pub-main { flex: 1; width: 100%; max-width: 1100px; margin: 0 auto; padding: 2rem 1.5rem 3rem; }
  @media (max-width: 768px) { .pub-main { padding: 1.5rem 1rem 2.5rem; } }

  nav {
    position: sticky; top: 0; z-index: 100;
    background: rgba(255,255,255,.95); backdrop-filter: blur(16px);
    border-bottom: 1px solid var(--border);
    padding: 0 1.75rem;
    height: 64px; display: flex; align-items: center; justify-content: space-between;
  }
  .nav-brand { font-size: 1.2rem; font-weight: 800; background: linear-gradient(135deg,var(--primary),var(--accent)); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; letter-spacing: -.03em; text-decoration: none; }
  .nav-links { display: flex; align-items: center; gap: 0.25rem; }
  .nav-links a { text-decoration: none; font-size: .875rem; font-weight: 500; padding: .4rem .75rem; border-radius: 8px; transition: color .15s, background .15s; }
  .nav-links a:hover { color: var(--text); background: var(--bg); }
  .btn-nav { padding: .5rem 1.1rem; border-radius: 8px; border: none; background: linear-gradient(135deg,var(--primary),var(--accent)); color: white; font-size: .875rem; font-weight: 700; cursor: pointer; text-decoration: none; transition: opacity .15s, transform .15s; box-shadow: 0 2px 8px rgba(86,37,209,.3); }
  .btn-nav:hover { opacity: .92; transform: translateY(-1px); }
  @media (max-width: 640px) { .nav-hide { display: none; } }

  /* ─── FOOTER ─── */
  footer { background: #202331; color: #64748b; text-align: center; padding: 3rem 1.5rem; font-size: .84rem; }
  footer strong { color: white; }
  .footer-links { display: flex; justify-content: center; align-items: center; gap: 1.5rem; margin-bottom: 1.25rem; flex-wrap: wrap; }
  .footer-links a { color: #64748b; text-decoration: none; font-weight: 500; transition: color .15s; }
  .footer-links a:hover { color: white; }
  .footer-divider { color: #3d4055; }
</style>
