<!--
  Generated by scripts/build-landing-i18n.js from landing/partials/{header,footer}.html
  and landing/partials/chrome.css — do not edit. Change the partial and re-run,
  so the landing pages and these pages keep the same nav and footer.
-->
<script>
  // Absolute, language-aware URLs from $lib/seo.js — see the generator for why
  // they are props rather than the %TOKEN%s the static pages use. `langs` is
  // langSwitchLinks(): [{ code, label, href, active }].
  let { homePath, catalogPath, brandPath, contactPath, langs = [], t, children } = $props()

  const appLogin = 'https://app.novaquiz.net/login'

  // `langs` only ever holds LANG_LABELS values from $lib/seo.js (never
  // request-derived), so this escaping is belt-and-braces rather than a real
  // taint concern — kept anyway so the {@html} below stays provably safe on
  // its own, without relying on that guarantee holding forever.
  function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c])
  }

  // Built here, not as static markup: the <select>'s onchange has to reach
  // the browser as plain HTML text (see SVELTE_LANG_SELECT in the generator),
  // and which <option> is selected still has to vary with `langs`.
  const langSelectHtml = $derived(
    '<select class="lang-select" onchange="nqSetLang(this.value)" aria-label="Language">' +
    langs.map(l => `<option value="${escapeHtml(l.code)}"${l.active ? ' selected' : ''}>${escapeHtml(l.label)}</option>`).join('') +
    '</select>'
  )
</script>

<div class="pub">
  <!-- Hand-written inline script, not Svelte-managed markup — see the note
       above SVELTE_EXPR for why this is safe under csr = false. -->
  <!-- eslint-disable-next-line svelte/no-at-html-tags -->
  {@html "<script>\n  function nqSetLang(input) {\n    var code, path;\n    if (input === 'en') { code = 'en'; path = '/en/exams'; }\n    else if (input === 'vi') { code = 'vi'; path = '/vi/exams'; }\n    else if (input === 'ja') { code = 'ja'; path = '/ja/exams'; }\n    else return;\n    document.cookie = 'nqlang=' + code + ';path=/;max-age=31536000;samesite=lax';\n    location.href = path;\n  }\n</script>"}
<nav>
  <a class="nav-brand" href={homePath}>NovaQuiz</a>
  <div class="nav-links">
    <a href={catalogPath} class="nav-hide">{t('nav.exams')}</a>
    <a href="{homePath}#features" class="nav-hide">{t('nav.features')}</a>
    <a href="{homePath}#security" class="nav-hide">{t('nav.security')}</a>
    <a href="{homePath}#how" class="nav-hide">{t('nav.how')}</a>
    <a href="{homePath}#faq" class="nav-hide">{t('nav.faq')}</a>
    <!-- eslint-disable-next-line svelte/no-at-html-tags -->
    {@html langSelectHtml}
    <a href={appLogin} class="btn-nav">{t('nav.cta')}</a>
  </div>
</nav>

<main class="pub-main">
  {@render children()}
</main>

<footer>
  <div class="footer-links">
    <a href={appLogin}>{t('nav.cta')}</a>
    <span class="footer-divider">·</span>
    <a href={catalogPath}>{t('nav.exams')}</a>
    <span class="footer-divider">·</span>
    <a href="{homePath}#features">{t('nav.features')}</a>
    <span class="footer-divider">·</span>
    <a href="{homePath}#faq">{t('nav.faq')}</a>
    <span class="footer-divider">·</span>
    <a href={brandPath}>{t('nav.brand')}</a>
    <span class="footer-divider">·</span>
    <a href={contactPath}>{t('nav.contact')}</a>
  </div>
  <p style="margin-bottom:.75rem">© 2026 <strong>NovaQuiz</strong> · <span>{t('footer.tagline')}</span></p>
  <p style="font-size:.8rem;opacity:.6">
    <span>{t('footer.builtBy')}</span> <strong style="color:#94a3b8">Trần Phú</strong>
    &nbsp;·&nbsp; <a href="mailto:tranphu.dev@gmail.com" style="color:#94a3b8;text-decoration:none">tranphu.dev@gmail.com</a>
    &nbsp;·&nbsp; <a href="https://novaquiz.net" style="color:#94a3b8;text-decoration:none">novaquiz.net</a>
  </p>
</footer>
</div>

<style>
  /* Tokens come from the :global(:root) block in src/routes/+layout.svelte,
     which is emitted whichever branch that layout renders. */
  .pub { min-height: 100vh; display: flex; flex-direction: column; background: var(--bg); color: var(--text); }
  .pub-main { flex: 1; width: 100%; max-width: 1100px; margin: 0 auto; padding: 2rem 1.5rem 3rem; }
  @media (max-width: 768px) { .pub-main { padding: 1.5rem 1rem 2.5rem; } }

  nav {
    position: sticky; top: 0; z-index: 100;
    background: rgba(255,255,255,.95); backdrop-filter: blur(16px);
    border-bottom: 1px solid var(--border);
    padding: 0 1.75rem;
    height: 64px; display: flex; align-items: center; justify-content: space-between;
  }
  .nav-brand { font-size: 1.2rem; font-weight: 800; background: linear-gradient(135deg,var(--primary),var(--accent)); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; letter-spacing: -.03em; text-decoration: none; }
  .nav-links { display: flex; align-items: center; gap: 0.25rem; }
  .nav-links a { text-decoration: none; font-size: .875rem; font-weight: 500; padding: .4rem .75rem; border-radius: 8px; transition: color .15s, background .15s; }
  .nav-links a:hover { color: var(--text); background: var(--bg); }
  .btn-nav { padding: .5rem 1.1rem; border-radius: 8px; border: none; background: linear-gradient(135deg,var(--primary),var(--accent)); color: white; font-size: .875rem; font-weight: 700; cursor: pointer; text-decoration: none; transition: opacity .15s, transform .15s; box-shadow: 0 2px 8px rgba(86,37,209,.3); }
  .btn-nav:hover { opacity: .92; transform: translateY(-1px); }
  @media (max-width: 640px) { .nav-hide { display: none; } }

  /* ─── LANG SELECT ─── */
  :global(.lang-select) {
    border: 1.5px solid var(--border); background: white; color: var(--muted);
    border-radius: 8px; padding: .4rem 1.9rem .4rem .7rem; font-size: .82rem; font-weight: 600;
    font-family: inherit; cursor: pointer; transition: all .15s;
    -webkit-appearance: none; -moz-appearance: none; appearance: none;
    background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%23595d72' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='6 9 12 15 18 9'%3E%3C/polyline%3E%3C/svg%3E");
    background-repeat: no-repeat; background-position: right .6rem center;
  }
  :global(.lang-select):hover { border-color: var(--accent); color: var(--primary); }
  :global(.lang-select):focus { outline: none; border-color: var(--accent); }

  /* ─── FOOTER ─── */
  footer { background: #202331; color: #64748b; text-align: center; padding: 3rem 1.5rem; font-size: .84rem; }
  footer strong { color: white; }
  .footer-links { display: flex; justify-content: center; align-items: center; gap: 1.5rem; margin-bottom: 1.25rem; flex-wrap: wrap; }
  .footer-links a { color: #64748b; text-decoration: none; font-weight: 500; transition: color .15s; }
  .footer-links a:hover { color: white; }
  .footer-divider { color: #3d4055; }
</style>
